# Generated by Django 3.2.4 on 2023-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_submittedtask_answer_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='myfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/image/')),
                ('college', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
